### PR TITLE
Add suport tor translations and Roboto font

### PR DESCRIPTION
**Pull request by mitjapotocin**
- added support for translations. 
- to use slovenian add `language: 'sl'` into the book frontmatter
- changed default font to `Roboto`

### CODE REVIEW

**Comment by janezd** [comment]
Translations work and č's are OK. I think @BlazZupan should confirm the change of font as well.

Minor comment: would it be possible to translate "Lecture Notes" at the top, so that it would be shown in the language of the current book? When a list is shown, English is OK. If this is difficult to change (I don't know whether it's possible and trivial to propagate these props upwards), then forget it.

**Review by janezd — APPROVED** [review]

**Comment by mitjapotocin** [comment]
@janezd could be done, but it's a strange UX. When clicking on `Zapiski` would change the language and take you to the list with only English books.

**Comment by janezd** [comment]
You're right.

Still, it would be nice if Slovenian books wouldn't have "Lecture notes" at the top. In part because I first didn't understand that this is a link to other notes; I thought it's a kind of title.

I suggest we think about some solution. Not urgent, though.

**Comment by mitjapotocin** [comment]
Should we go with [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro) fonts?
This fonts are going to be on the new website https://www.figma.com/file/W4gNurcpTxmRfLPKalCqBg/Orange-website?node-id=46-107&t=N6X1b6ogRk8JQDjn-0

**Pull request merged**
